#ifndef SPRITESHEET_ID_H
#define SPRITESHEET_ID_H

enum class SpritesheetID {
    NOVAL = -1,
    DIALOGUE_BOX,
    DEFAULT_TILESET,
    PLAYER_SPRITESHEET,
    CHECKPOINT,
    WEAPON_PICKUP,
    JUMP_PICKUP,
    BOOTS_PICKUP,
    WALLJUMP_PICKUP,
    PROJECTILE,
    FLAG,
    ENGINE_SPRITESHEET,
    SPLASH_SCREEN
};

#endif